### ISSUE TITLE
Blocking of "Created" Pop-up

### ISSUE THREAD

**Issue by eokw** [poowf/invoiceneko#106]
After creating invoice etc, the "invoice created" pop up will stay on the screen until pressing the cross button. And while the pop-up is not remove, it continues to block other parts of the website, eg other pop-ups, or website buttons

![pop_up_blocked_by_created_message](https://user-images.githubusercontent.com/23492766/48950390-f1199d80-ef75-11e8-93f2-72c8b9897b8f.jpg)
![pop_up_blocked_by_created_message3](https://user-images.githubusercontent.com/23492766/48950391-f1b23400-ef75-11e8-9011-0eadbb0e4d94.jpg)
![pop_up_blocked_by_created_message2](https://user-images.githubusercontent.com/23492766/48950393-f1b23400-ef75-11e8-8c7b-c8932c122328.jpg)

**Comment by thelaraman** [comment]
I'll have a look at it

**Comment by zanechua** [comment]
Possibly need an alternate notification that conforms with Material Design

**Comment by zanechua** [comment]
Adjustment of snackbars to disappear after 6 seconds
