### ISSUE TITLE
Overlapping of Pop-up of Buttons

### ISSUE THREAD

**Issue by eokw** [poowf/invoiceneko#107]
On company/roles , the pop-up of each icons seem to be slightly slower such that as cursor move to next icon, the previous pop-up will be overlapping with the next pop-up for an obvious short period.

![company_roles_popup_overlap](https://user-images.githubusercontent.com/23492766/48950513-5a011580-ef76-11e8-8053-03946b858975.jpg)

**Comment by thelaraman** [comment]
I will check this

**Comment by thelaraman** [comment]
I have a PR for this

**Comment by zanechua** [comment]
Fixed in
https://github.com/poowf/invoiceneko/commit/64d77a08a9f5f3b05c24a5b33f32d8156c20e0d2
