### ISSUE TITLE
Missing "Add Company" Menu Button

### ISSUE THREAD

**Issue by eokw** [poowf/invoiceneko#108]
Missing "add company" menu item when screen is smaller.

![missing_add_company](https://user-images.githubusercontent.com/23492766/48950560-8ddc3b00-ef76-11e8-93b0-18466dc3ca56.jpg)
![missing_add_company2](https://user-images.githubusercontent.com/23492766/48950621-c24ff700-ef76-11e8-87f9-155f8b649f06.jpg)

**Comment by thelaraman** [comment]
I have a PR pending for this

**Comment by zanechua** [comment]
Implemented in
https://github.com/poowf/invoiceneko/commit/89353991a6146e29898c5e0da18fbeaf10106834
