### ISSUE TITLE
[BUG] - blank page - docker

### ISSUE THREAD

**Issue by jenaye** [poowf/invoiceneko#198]
Hi, i tried to install the tool and i got blank page and this stack-trace, can you fix it ? 

![image](https://user-images.githubusercontent.com/15458329/136122722-3ff829d1-3d20-40bc-a2a9-fd337b21293a.png)

![image](https://user-images.githubusercontent.com/15458329/136123066-c7bd6c54-2e5b-40a3-a11e-888e522765d9.png)

Also, can be nice to add some screenshot of the application or maybe demo idk

Peace
Jenaye,

**Comment by jenaye** [comment]
Lil update, my bad, 

I forgot to copy the .env file

but I have another stacktrace, i had to `sudo chmod -R ugo+rw storage` and do the same for the folder bootstrap

and we have 

![image](https://user-images.githubusercontent.com/15458329/136124129-2722a72a-5e77-4323-8dba-25cc48bc1010.png)


i took ure in fake .env to test skip this step and now i got this error : 

![image](https://user-images.githubusercontent.com/15458329/136124422-3c8a034d-c17f-423b-82b1-e5c49551e318.png)

**Comment by zanechua** [comment]
Hey @jenaye,

What exactly are you using?

`docker run` ?

The `docker-compose` is an environment image at the moment, not really meant for production usage.

Please see:

https://github.com/poowf/invoiceneko/blob/develop/resources/docs/1.0/development.md


This is not really a bug, would be good if we can move this to discussions.
