### ISSUE TITLE
Invoice Previews

### ISSUE THREAD

**Issue by Snowpea98** [poowf/invoiceneko#37]
Allow previewing and updating/making one off exceptions of future individual invoices, by creating a buffer of the next 1 or 2 impending invoices

**Comment by zanechua** [comment]
Partial implementation:
https://github.com/poowf/invoiceneko/commit/9d9de2c1444484e0e033a85f0beef9b34f84fe41

**Comment by zanechua** [comment]
Implemented in:
https://github.com/poowf/invoiceneko/commit/02aa39018e290c08c59fb068b3270afa49df0133
