### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by zanechua** [poowf/invoiceneko#48]

**Comment by kosciak9** [comment]
Hey, I'm going to look into it today.

**Comment by kosciak9** [comment]
```

**Comment by zanechua** [comment]
Dockerfile implemented in:
https://github.com/poowf/invoiceneko/commit/749198b465fc860571362dd385d50eb674988e77

Image is available on Docker Hub:
https://hub.docker.com/r/poowf/invoiceneko

This is a self-contained image with nginx, php 7.2 and mysql.

Not really recommended to be running this and there are some issues e.g. missing smtp configuration that will throw a 500 error upon user registration. There is a need to refactor some of the original code to catch these exceptions or make it configurable so that it does not break locally.

Will move to a docker compose configuration in the near future.
