### ISSUE TITLE
Quantity is zero for invoice

### ISSUE THREAD

**Issue by emilyolm** [poowf/invoiceneko#70]
![image](https://user-images.githubusercontent.com/5109630/48480516-a9906480-e845-11e8-97e4-4151dca2b485.png)

Even though quantity is set at 0 for invoice, it is still allowed to proceed.

**Comment by zanechua** [comment]
Fixed in:
https://github.com/poowf/invoiceneko/commit/c753ef0764394e9e7fbc4c7e2c3397b16585d6eb
