### ISSUE TITLE
 quotation status is still draft even though it has been updated

### ISSUE THREAD

**Issue by emilyolm** [poowf/invoiceneko#73]
![image](https://user-images.githubusercontent.com/5109630/48480612-012ed000-e846-11e8-84f0-3e35807f42c2.png)

quotation status is still draft even though it has been updated.

**Comment by zanechua** [comment]
Fixed in:
https://github.com/poowf/invoiceneko/commit/c753ef0764394e9e7fbc4c7e2c3397b16585d6eb
