### ISSUE TITLE
Information disappear too slowly.

### ISSUE THREAD

**Issue by emilyolm** [poowf/invoiceneko#74]
![image](https://user-images.githubusercontent.com/5109630/48480668-26bbd980-e846-11e8-9da5-4d826cc19fbb.png)

Information disappear too slowly. should you consider adding a cross button?

**Comment by zanechua** [comment]
Fixed in:
https://github.com/poowf/invoiceneko/commit/c753ef0764394e9e7fbc4c7e2c3397b16585d6eb
