### ISSUE TITLE
message button blocking

### ISSUE THREAD

**Issue by emilyolm** [poowf/invoiceneko#76]
![image](https://user-images.githubusercontent.com/5109630/48480899-cbd6b200-e846-11e8-8095-7c2ba2bed3c1.png)

can you shift it to bottom left or right? it's blocking the words.

**Comment by zanechua** [comment]
Won't fix this at the moment due to temporarily disabling of the tawk.to chat, May need to think up of an alternative as tawk.to does not allow modification of the positioning of the chat element
