### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by emilyolm** [poowf/invoiceneko#79]
![image](https://user-images.githubusercontent.com/5109630/48481188-a302ec80-e847-11e8-94b7-def56c338a46.png)

1. What if they pay cash as option?

2. crash when log payment.

**Comment by zanechua** [comment]
Fixed in:
https://github.com/poowf/invoiceneko/commit/c753ef0764394e9e7fbc4c7e2c3397b16585d6eb
